name: style check
on:
  push:
    branches:
      - 'Release_Branch/Axion'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ESLint
      run: |
        cd AntraShare
        npm install
        npm run lint
